site_name: AristElearning
nav:
    - Giới thiệu: index.rst
theme: readthedocs
use_directory_urls: true
site_url: null
repo_url: null
repo_name: 'hai'
extra_css: [custom/extra.css]
formats:
  - epub
  - pdf