site_name: Arist Elearning
nav:
    - Giới thiệu: index.rst
    
    - Hướng dẩn sử dụng:
      
theme: readthedocs
use_directory_urls: true
site_url: null
repo_url: null
repo_name: 'hai'
extra_css: [custom/extra.css]
formats:
  - epub
  - pdf

